"""The chemist's counter — 55 real SKUs a Delhi neighbourhood pharmacy actually dispenses.

Prices are Delhi MRPs, 2026, expressed in **paise**. Chemist margins run opposite to a kirana's:
the branded prescription strip that drives footfall earns a thin, stockist-fixed 12-18%, while
the wellness jar, the ayurveda shelf and the BP monitor beside the till earn 20-35% and quietly
pay the rent. ``cost_paise`` values below are placeholders — :func:`at_trade_margin` re-derives
every cost into its category band, exactly as the kirana module prices itself.

``popularity`` is a *relative* pick weight inside a category (cross-category mix lives in
:data:`CATEGORY_SHARES`). ``festival_affinity`` lifts only the gift-shaped wellness SKUs —
Chyawanprash and Horlicks move in the Diwali-to-winter window, Dolo moves all year.
"""

from __future__ import annotations

from typing import Final

from munshiji.seed.catalog import CatalogItem, ShopCatalog, at_trade_margin

__all__ = [
    "CATEGORIES",
    "CATEGORY_LABELS_HI",
    "CATEGORY_MARGIN_TARGET",
    "CATEGORY_SHARES",
    "CO_OCCURRENCE",
    "PHARMACY_CATALOG",
]


#: Canonical category order. Every uplift / share table is keyed on exactly these.
CATEGORIES: Final[tuple[str, ...]] = (
    "otc",
    "prescription",
    "wellness",
    "baby_care",
    "personal_care",
    "devices",
    "ayurveda",
)

CATEGORY_LABELS_HI: Final[dict[str, str]] = {
    "otc": "आम दवाइयाँ",
    "prescription": "पर्ची की दवाइयाँ",
    "wellness": "विटामिन-सप्लीमेंट",
    "baby_care": "बेबी केयर",
    "personal_care": "पर्सनल केयर",
    "devices": "हेल्थ डिवाइस",
    "ayurveda": "आयुर्वेद",
}

#: Share of basket *lines* by category. Sums to 1.0. Medicines dominate — a chemist is a chemist
#: first — but the front-of-counter shelves (wellness, baby, personal care) carry real weight.
CATEGORY_SHARES: Final[dict[str, float]] = {
    "otc": 0.28,
    "prescription": 0.24,
    "wellness": 0.13,
    "baby_care": 0.10,
    "personal_care": 0.10,
    "devices": 0.06,
    "ayurveda": 0.09,
}

#: Given the basket's anchor category, where the *next* line comes from. Each row sums to 1.0.
#: A prescription pulls OTC add-ons (the paracetamol beside the antibiotic); baby food pulls
#: diapers; a BP monitor is bought by someone already filling a blood-pressure prescription.
CO_OCCURRENCE: Final[dict[str, dict[str, float]]] = {
    "otc": {
        "otc": 0.30,
        "prescription": 0.16,
        "wellness": 0.14,
        "personal_care": 0.12,
        "ayurveda": 0.10,
        "baby_care": 0.10,
        "devices": 0.08,
    },
    "prescription": {
        "otc": 0.30,
        "prescription": 0.24,
        "wellness": 0.14,
        "devices": 0.12,
        "personal_care": 0.08,
        "ayurveda": 0.06,
        "baby_care": 0.06,
    },
    "wellness": {
        "wellness": 0.22,
        "otc": 0.22,
        "prescription": 0.18,
        "ayurveda": 0.14,
        "personal_care": 0.10,
        "devices": 0.08,
        "baby_care": 0.06,
    },
    "baby_care": {
        "baby_care": 0.34,
        "otc": 0.18,
        "wellness": 0.14,
        "personal_care": 0.14,
        "prescription": 0.10,
        "ayurveda": 0.06,
        "devices": 0.04,
    },
    "personal_care": {
        "personal_care": 0.28,
        "otc": 0.20,
        "baby_care": 0.14,
        "wellness": 0.14,
        "prescription": 0.10,
        "ayurveda": 0.10,
        "devices": 0.04,
    },
    "devices": {
        "prescription": 0.34,
        "otc": 0.20,
        "wellness": 0.16,
        "devices": 0.14,
        "ayurveda": 0.06,
        "personal_care": 0.06,
        "baby_care": 0.04,
    },
    "ayurveda": {
        "ayurveda": 0.26,
        "wellness": 0.20,
        "otc": 0.20,
        "prescription": 0.12,
        "personal_care": 0.10,
        "baby_care": 0.06,
        "devices": 0.06,
    },
}


#: Gross-margin band per category, as a share of the selling price.
#:
#: A chemist sells at printed MRP — the customer reads the pack as readily as the shopkeeper —
#: so the margin is whatever the stockist's trade scheme leaves. Branded prescription drugs are
#: the tightest shelf in the shop (the 12-18% here is the classic retail trade margin); baby food
#: is tighter still because Nestlé and P&G concede almost nothing. Wellness, devices and ayurveda
#: are where the counter earns, which is exactly the spread the margin-leak engine goes hunting for.
CATEGORY_MARGIN_TARGET: Final[dict[str, tuple[float, float]]] = {
    "baby_care": (0.08, 0.14),
    "prescription": (0.12, 0.18),
    "otc": (0.16, 0.24),
    "personal_care": (0.18, 0.26),
    "devices": (0.20, 0.30),
    "ayurveda": (0.22, 0.32),
    "wellness": (0.25, 0.35),
}


# ─────────────────────────────────────────────────────────────────────────────
# The counter
# ─────────────────────────────────────────────────────────────────────────────

#: Shelf prices as listed. Trade margins are applied afterwards by :func:`at_trade_margin`,
#: which is what produces the exported ``PHARMACY_CATALOG``.
_LISTED: Final[tuple[CatalogItem, ...]] = (
    # ── otc ─────────────────────────────────────────────────────────────────
    CatalogItem(
        sku="PH-DOLO-650",
        name="Dolo 650 (15 tabs)",
        name_hi="डोलो 650 (15 गोली)",
        category="otc",
        unit="strip",
        cost_paise=2_700,
        sell_paise=3_400,
        popularity=2.60,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-CROCIN-ADV",
        name="Crocin Advance 500 (20 tabs)",
        name_hi="क्रोसिन एडवांस 500 (20 गोली)",
        category="otc",
        unit="strip",
        cost_paise=4_600,
        sell_paise=5_700,
        popularity=1.60,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-COMBIFLAM-20",
        name="Combiflam (20 tabs)",
        name_hi="कॉम्बिफ्लेम (20 गोली)",
        category="otc",
        unit="strip",
        cost_paise=4_400,
        sell_paise=5_500,
        popularity=1.80,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-CALPOL-SYP",
        name="Calpol 250 Paediatric Syrup 60ml",
        name_hi="कैलपोल 250 बच्चों की सिरप 60 मि.ली.",
        category="otc",
        unit="bottle",
        cost_paise=3_600,
        sell_paise=4_500,
        popularity=1.10,
        qty_choices=(1.0,),
        is_perishable=True,
        shelf_life_days=240,
    ),
    CatalogItem(
        sku="PH-ELECTRAL-ORS",
        name="Electral ORS Sachet 21.8g",
        name_hi="इलेक्ट्रल ओआरएस पाउच",
        category="otc",
        unit="sachet",
        cost_paise=1_800,
        sell_paise=2_200,
        popularity=1.40,
        qty_choices=(1.0, 2.0),
        is_perishable=True,
        shelf_life_days=365,
    ),
    CatalogItem(
        sku="PH-VICKS-50G",
        name="Vicks VapoRub 50ml",
        name_hi="विक्स वेपोरब 50 मि.ली.",
        category="otc",
        unit="jar",
        cost_paise=13_200,
        sell_paise=16_500,
        popularity=1.10,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-VOLINI-SPRAY",
        name="Volini Pain Relief Spray 100g",
        name_hi="वोलिनी स्प्रे 100 ग्राम",
        category="otc",
        unit="bottle",
        cost_paise=31_900,
        sell_paise=39_900,
        popularity=0.90,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-MOOV-50G",
        name="Moov Pain Relief Cream 50g",
        name_hi="मूव क्रीम 50 ग्राम",
        category="otc",
        unit="tube",
        cost_paise=18_800,
        sell_paise=23_500,
        popularity=0.80,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-BETADINE-20G",
        name="Betadine 10% Ointment 20g",
        name_hi="बीटाडीन मरहम 20 ग्राम",
        category="otc",
        unit="tube",
        cost_paise=10_800,
        sell_paise=13_500,
        popularity=0.70,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-DETTOL-550",
        name="Dettol Antiseptic Liquid 550ml",
        name_hi="डेटॉल एंटीसेप्टिक 550 मि.ली.",
        category="otc",
        unit="bottle",
        cost_paise=18_400,
        sell_paise=23_000,
        popularity=1.00,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-BANDAID-20",
        name="Band-Aid Washproof (20 strips)",
        name_hi="बैंड-एड वॉशप्रूफ (20 पट्टी)",
        category="otc",
        unit="box",
        cost_paise=7_600,
        sell_paise=9_500,
        popularity=0.90,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-DIGENE-MINT",
        name="Digene Mint (15 tabs)",
        name_hi="डाइजीन मिंट (15 गोली)",
        category="otc",
        unit="strip",
        cost_paise=2_200,
        sell_paise=2_800,
        popularity=1.30,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-BENADRYL-150",
        name="Benadryl Cough Syrup 150ml",
        name_hi="बेनाड्रिल कफ सिरप 150 मि.ली.",
        category="otc",
        unit="bottle",
        cost_paise=10_800,
        sell_paise=13_500,
        popularity=1.00,
        qty_choices=(1.0,),
        is_perishable=True,
        shelf_life_days=270,
    ),
    CatalogItem(
        sku="PH-OTRIVIN-10ML",
        name="Otrivin Adult Nasal Spray 10ml",
        name_hi="ओट्रिविन नेज़ल स्प्रे 10 मि.ली.",
        category="otc",
        unit="bottle",
        cost_paise=8_400,
        sell_paise=10_500,
        popularity=0.80,
        qty_choices=(1.0,),
        is_perishable=True,
        shelf_life_days=240,
    ),
    # ── prescription ────────────────────────────────────────────────────────
    CatalogItem(
        sku="PH-AZITHRAL-500",
        name="Azithral 500 (5 tabs)",
        name_hi="एज़िथ्रल 500 (5 गोली)",
        category="prescription",
        unit="strip",
        cost_paise=10_200,
        sell_paise=12_000,
        popularity=1.40,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-PAN-D-15",
        name="Pan-D (15 caps)",
        name_hi="पैन-डी (15 कैप्सूल)",
        category="prescription",
        unit="strip",
        cost_paise=16_900,
        sell_paise=19_900,
        popularity=1.80,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-TELMA-40",
        name="Telma 40 (30 tabs)",
        name_hi="टेल्मा 40 (30 गोली)",
        category="prescription",
        unit="strip",
        cost_paise=20_000,
        sell_paise=23_500,
        popularity=1.50,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-GLYCOMET-500",
        name="Glycomet 500 SR (30 tabs)",
        name_hi="ग्लाइकोमेट 500 एसआर (30 गोली)",
        category="prescription",
        unit="strip",
        cost_paise=5_500,
        sell_paise=6_500,
        popularity=1.70,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-ECOSPRIN-75",
        name="Ecosprin 75 (14 tabs)",
        name_hi="इकोस्प्रिन 75 (14 गोली)",
        category="prescription",
        unit="strip",
        cost_paise=850,
        sell_paise=1_000,
        popularity=1.60,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-ASCORIL-LS",
        name="Ascoril LS Syrup 100ml",
        name_hi="एस्कोरिल एलएस सिरप 100 मि.ली.",
        category="prescription",
        unit="bottle",
        cost_paise=11_500,
        sell_paise=13_500,
        popularity=1.20,
        qty_choices=(1.0,),
        is_perishable=True,
        shelf_life_days=270,
    ),
    CatalogItem(
        sku="PH-AUGMENTIN-625",
        name="Augmentin 625 Duo (10 tabs)",
        name_hi="ऑगमेंटिन 625 डुओ (10 गोली)",
        category="prescription",
        unit="strip",
        cost_paise=19_100,
        sell_paise=22_500,
        popularity=1.00,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-THYRONORM-50",
        name="Thyronorm 50mcg (120 tabs)",
        name_hi="थायरोनॉर्म 50 (120 गोली)",
        category="prescription",
        unit="bottle",
        cost_paise=15_700,
        sell_paise=18_500,
        popularity=1.20,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-MONTAIR-LC",
        name="Montair LC (15 tabs)",
        name_hi="मोंटेयर एलसी (15 गोली)",
        category="prescription",
        unit="strip",
        cost_paise=21_700,
        sell_paise=25_500,
        popularity=0.90,
        qty_choices=(1.0,),
    ),
    # ── wellness ────────────────────────────────────────────────────────────
    CatalogItem(
        sku="PH-REVITAL-H-30",
        name="Revital H (30 caps)",
        name_hi="रिवाइटल एच (30 कैप्सूल)",
        category="wellness",
        unit="bottle",
        cost_paise=25_200,
        sell_paise=36_000,
        popularity=1.30,
        qty_choices=(1.0,),
        festival_affinity=1.15,
    ),
    CatalogItem(
        sku="PH-ZINCOVIT-15",
        name="Zincovit (15 tabs)",
        name_hi="ज़िंकोविट (15 गोली)",
        category="wellness",
        unit="strip",
        cost_paise=7_700,
        sell_paise=11_000,
        popularity=1.50,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-SHELCAL-500",
        name="Shelcal 500 (15 tabs)",
        name_hi="शेलकैल 500 (15 गोली)",
        category="wellness",
        unit="strip",
        cost_paise=8_800,
        sell_paise=12_500,
        popularity=1.40,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-LIMCEE-500",
        name="Limcee Vitamin C Chewable (15 tabs)",
        name_hi="लिम्सी विटामिन सी (15 गोली)",
        category="wellness",
        unit="strip",
        cost_paise=1_900,
        sell_paise=2_700,
        popularity=1.00,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-BECOSULES-20",
        name="Becosules (20 caps)",
        name_hi="बीकोस्यूल्स (20 कैप्सूल)",
        category="wellness",
        unit="strip",
        cost_paise=3_900,
        sell_paise=5_600,
        popularity=1.20,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-HORLICKS-500",
        name="Horlicks Classic Malt 500g Jar",
        name_hi="हॉर्लिक्स क्लासिक 500 ग्राम",
        category="wellness",
        unit="jar",
        cost_paise=19_300,
        sell_paise=27_500,
        popularity=1.10,
        qty_choices=(1.0,),
        festival_affinity=1.20,
    ),
    CatalogItem(
        sku="PH-ENSURE-400",
        name="Ensure Vanilla 400g",
        name_hi="एन्श्योर वनीला 400 ग्राम",
        category="wellness",
        unit="jar",
        cost_paise=50_400,
        sell_paise=72_000,
        popularity=0.50,
        qty_choices=(1.0,),
    ),
    # ── baby_care ───────────────────────────────────────────────────────────
    CatalogItem(
        sku="PH-PAMPERS-M42",
        name="Pampers All Round Pants M (42)",
        name_hi="पैम्पर्स पैंट्स M (42 पीस)",
        category="baby_care",
        unit="pack",
        cost_paise=62_200,
        sell_paise=69_900,
        popularity=1.40,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-CERELAC-WHEAT",
        name="Cerelac Wheat 300g",
        name_hi="सेरेलैक गेहूं 300 ग्राम",
        category="baby_care",
        unit="pack",
        cost_paise=28_000,
        sell_paise=31_500,
        popularity=1.20,
        qty_choices=(1.0,),
        is_perishable=True,
        shelf_life_days=300,
    ),
    CatalogItem(
        sku="PH-LACTOGEN-1",
        name="Nestle Lactogen 1 400g",
        name_hi="लैक्टोजन 1 (400 ग्राम)",
        category="baby_care",
        unit="pack",
        cost_paise=40_500,
        sell_paise=45_500,
        popularity=1.00,
        qty_choices=(1.0,),
        is_perishable=True,
        shelf_life_days=365,
    ),
    CatalogItem(
        sku="PH-JJ-BABYOIL",
        name="Johnson's Baby Oil 200ml",
        name_hi="जॉनसन बेबी ऑयल 200 मि.ली.",
        category="baby_care",
        unit="bottle",
        cost_paise=20_900,
        sell_paise=23_500,
        popularity=0.90,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-HIM-BABYLOTION",
        name="Himalaya Baby Lotion 200ml",
        name_hi="हिमालया बेबी लोशन 200 मि.ली.",
        category="baby_care",
        unit="bottle",
        cost_paise=18_700,
        sell_paise=21_000,
        popularity=0.80,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-JJ-BABYPOWDER",
        name="Johnson's Baby Powder 200g",
        name_hi="जॉनसन बेबी पाउडर 200 ग्राम",
        category="baby_care",
        unit="bottle",
        cost_paise=16_900,
        sell_paise=19_000,
        popularity=0.70,
        qty_choices=(1.0,),
    ),
    # ── personal_care ───────────────────────────────────────────────────────
    CatalogItem(
        sku="PH-DOVE-SOAP",
        name="Dove Cream Beauty Bar 100g",
        name_hi="डव साबुन 100 ग्राम",
        category="personal_care",
        unit="bar",
        cost_paise=5_300,
        sell_paise=6_800,
        popularity=1.30,
        qty_choices=(1.0, 2.0),
    ),
    CatalogItem(
        sku="PH-COLGATE-200",
        name="Colgate Strong Teeth 200g",
        name_hi="कोलगेट स्ट्रॉन्ग टीथ 200 ग्राम",
        category="personal_care",
        unit="tube",
        cost_paise=10_500,
        sell_paise=13_500,
        popularity=1.40,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-SENSODYNE-75",
        name="Sensodyne Fresh Gel 75g",
        name_hi="सेंसोडाइन फ्रेश जेल 75 ग्राम",
        category="personal_care",
        unit="tube",
        cost_paise=15_200,
        sell_paise=19_500,
        popularity=0.90,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-WHISPER-XL30",
        name="Whisper Ultra Clean XL (30 pads)",
        name_hi="व्हिस्पर अल्ट्रा XL (30 पैड)",
        category="personal_care",
        unit="pack",
        cost_paise=27_200,
        sell_paise=34_900,
        popularity=1.20,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-STAYFREE-XL40",
        name="Stayfree Secure XL (40 pads)",
        name_hi="स्टेफ्री सिक्योर XL (40 पैड)",
        category="personal_care",
        unit="pack",
        cost_paise=24_900,
        sell_paise=31_900,
        popularity=1.00,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-MAMAEARTH-FW",
        name="Mamaearth Ubtan Face Wash 100ml",
        name_hi="मामाअर्थ उबटन फेस वॉश 100 मि.ली.",
        category="personal_care",
        unit="bottle",
        cost_paise=20_200,
        sell_paise=25_900,
        popularity=0.70,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-DETTOL-SOAP",
        name="Dettol Original Soap 125g",
        name_hi="डेटॉल साबुन 125 ग्राम",
        category="personal_care",
        unit="bar",
        cost_paise=5_900,
        sell_paise=7_500,
        popularity=1.10,
        qty_choices=(1.0, 2.0),
    ),
    # ── devices ─────────────────────────────────────────────────────────────
    CatalogItem(
        sku="PH-BP02-MONITOR",
        name="Dr Morepen BP-02 Blood Pressure Monitor",
        name_hi="डॉ. मोरपेन BP-02 बीपी मॉनिटर",
        category="devices",
        unit="piece",
        cost_paise=138_800,
        sell_paise=185_000,
        popularity=1.20,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-DIGI-THERMO",
        name="Dr Morepen Digital Thermometer",
        name_hi="डिजिटल थर्मामीटर",
        category="devices",
        unit="piece",
        cost_paise=14_900,
        sell_paise=19_900,
        popularity=1.40,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-ACCUCHEK-50",
        name="Accu-Chek Active Strips (50)",
        name_hi="एक्यू-चेक एक्टिव स्ट्रिप्स (50)",
        category="devices",
        unit="box",
        cost_paise=78_800,
        sell_paise=105_000,
        popularity=1.00,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-PULSE-OXI",
        name="Dr Trust Pulse Oximeter",
        name_hi="पल्स ऑक्सीमीटर",
        category="devices",
        unit="piece",
        cost_paise=97_400,
        sell_paise=129_900,
        popularity=0.50,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-NEBU-MASK",
        name="Nebulizer Mask Kit (Adult)",
        name_hi="नेबुलाइज़र मास्क किट",
        category="devices",
        unit="piece",
        cost_paise=11_300,
        sell_paise=15_000,
        popularity=0.60,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-CREPE-10CM",
        name="Flamingo Crepe Bandage 10cm",
        name_hi="क्रेप बैंडेज 10 से.मी.",
        category="devices",
        unit="piece",
        cost_paise=12_400,
        sell_paise=16_500,
        popularity=0.70,
        qty_choices=(1.0,),
    ),
    # ── ayurveda ────────────────────────────────────────────────────────────
    CatalogItem(
        sku="PH-DABUR-CHYW",
        name="Dabur Chyawanprash 1kg",
        name_hi="डाबर च्यवनप्राश 1 किलो",
        category="ayurveda",
        unit="jar",
        cost_paise=31_000,
        sell_paise=42_500,
        popularity=1.40,
        qty_choices=(1.0,),
        is_perishable=True,
        shelf_life_days=365,
        festival_affinity=1.30,
    ),
    CatalogItem(
        sku="PH-LIV52-100",
        name="Himalaya Liv.52 (100 tabs)",
        name_hi="हिमालया लिव-52 (100 गोली)",
        category="ayurveda",
        unit="bottle",
        cost_paise=13_100,
        sell_paise=18_000,
        popularity=1.10,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-BAIDYA-TRIPHALA",
        name="Baidyanath Triphala Churna 120g",
        name_hi="बैद्यनाथ त्रिफला चूर्ण 120 ग्राम",
        category="ayurveda",
        unit="pack",
        cost_paise=8_800,
        sell_paise=12_000,
        popularity=0.80,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-PTJ-HONEY-500",
        name="Patanjali Honey 500g",
        name_hi="पतंजलि शहद 500 ग्राम",
        category="ayurveda",
        unit="bottle",
        cost_paise=12_000,
        sell_paise=16_500,
        popularity=1.00,
        qty_choices=(1.0,),
        festival_affinity=1.15,
    ),
    CatalogItem(
        sku="PH-ZANDU-BALM",
        name="Zandu Balm 25ml",
        name_hi="झंडू बाम 25 मि.ली.",
        category="ayurveda",
        unit="jar",
        cost_paise=8_400,
        sell_paise=11_500,
        popularity=1.20,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="PH-HAJMOLA-120",
        name="Dabur Hajmola Regular (120 tabs)",
        name_hi="डाबर हाजमोला (120 गोली)",
        category="ayurveda",
        unit="bottle",
        cost_paise=6_900,
        sell_paise=9_500,
        popularity=0.90,
        qty_choices=(1.0,),
    ),
)


PHARMACY_CATALOG: Final[ShopCatalog] = ShopCatalog(
    key="pharmacy",
    categories=CATEGORIES,
    labels_hi=CATEGORY_LABELS_HI,
    shares=CATEGORY_SHARES,
    co_occurrence=CO_OCCURRENCE,
    margin_targets=CATEGORY_MARGIN_TARGET,
    items=at_trade_margin(_LISTED, CATEGORY_MARGIN_TARGET),
)
PHARMACY_CATALOG.validate()
