"""The mobile counter — 48 real SKUs a Karol Bagh accessories shop actually stocks.

Prices are Delhi street MRPs, 2026, in **paise**. Accessory economics are the kirana's inverse:
the unbranded shelf carries the shop — a ₹149 printed cover or ₹99 tempered glass earns 40-55%
while a branded SanDisk card earns 12-18% and exists mostly so the customer does not walk to the
next counter. Costs are derived from :data:`CATEGORY_MARGIN_TARGET` via :func:`at_trade_margin`.
"""

from __future__ import annotations

from typing import Final

from munshiji.seed.catalog import CatalogItem, ShopCatalog, at_trade_margin

__all__ = [
    "CATEGORIES",
    "CATEGORY_LABELS_HI",
    "CATEGORY_MARGIN_TARGET",
    "CATEGORY_SHARES",
    "CO_OCCURRENCE",
    "MOBILE_CATALOG",
]


#: Canonical category order. Every uplift / share table is keyed on exactly these.
CATEGORIES: Final[tuple[str, ...]] = (
    "chargers",
    "audio",
    "covers",
    "screen_guards",
    "storage",
    "accessories",
)

CATEGORY_LABELS_HI: Final[dict[str, str]] = {
    "chargers": "चार्जर-केबल",
    "audio": "इयरफ़ोन-स्पीकर",
    "covers": "कवर-केस",
    "screen_guards": "स्क्रीन गार्ड",
    "storage": "मेमोरी-पेनड्राइव",
    "accessories": "एक्सेसरीज़",
}

#: Share of basket *lines* by category. Sums to 1.0.
CATEGORY_SHARES: Final[dict[str, float]] = {
    "chargers": 0.26,
    "audio": 0.22,
    "covers": 0.20,
    "screen_guards": 0.12,
    "storage": 0.10,
    "accessories": 0.10,
}

#: Given the basket's anchor category, where the *next* line comes from. Each row sums to 1.0.
#: A new cover pulls a screen guard; a charger pulls a cable; audio pulls storage rarely.
CO_OCCURRENCE: Final[dict[str, dict[str, float]]] = {
    "chargers": {
        "chargers": 0.30,
        "audio": 0.16,
        "accessories": 0.16,
        "covers": 0.14,
        "screen_guards": 0.12,
        "storage": 0.12,
    },
    "audio": {
        "audio": 0.24,
        "chargers": 0.22,
        "accessories": 0.20,
        "covers": 0.16,
        "screen_guards": 0.12,
        "storage": 0.06,
    },
    "covers": {
        "screen_guards": 0.34,
        "covers": 0.16,
        "chargers": 0.14,
        "accessories": 0.14,
        "audio": 0.12,
        "storage": 0.10,
    },
    "screen_guards": {
        "covers": 0.30,
        "screen_guards": 0.18,
        "chargers": 0.16,
        "accessories": 0.14,
        "audio": 0.12,
        "storage": 0.10,
    },
    "storage": {
        "chargers": 0.22,
        "accessories": 0.20,
        "storage": 0.18,
        "audio": 0.16,
        "covers": 0.14,
        "screen_guards": 0.10,
    },
    "accessories": {
        "accessories": 0.22,
        "chargers": 0.20,
        "audio": 0.18,
        "covers": 0.16,
        "screen_guards": 0.12,
        "storage": 0.12,
    },
}


#: Gross-margin band per category, as a share of the selling price.
#:
#: The spread is the point, and here it is fat where the kirana's is thin. Unbranded covers and
#: tempered glass are near pure margin — the customer has no reference price. Branded audio and
#: chargers are healthy but comparison-shopped; branded storage is a courtesy line the shop
#: matches to online pricing and barely earns on. The blended result lands near 30%.
CATEGORY_MARGIN_TARGET: Final[dict[str, tuple[float, float]]] = {
    "storage": (0.12, 0.18),
    "audio": (0.22, 0.32),
    "chargers": (0.25, 0.35),
    "accessories": (0.30, 0.42),
    "covers": (0.35, 0.50),
    "screen_guards": (0.40, 0.55),
}


# ─────────────────────────────────────────────────────────────────────────────
# The shelf
# ─────────────────────────────────────────────────────────────────────────────

#: Shelf prices as listed. Trade margins are applied afterwards by :func:`at_trade_margin`,
#: which is what produces the exported ``MOBILE_CATALOG``.
_LISTED: Final[tuple[CatalogItem, ...]] = (
    # ── chargers (wall, car, cables, power banks) ───────────────────────────
    CatalogItem(
        sku="MB-MI-33W",
        name="Mi 33W SonicCharge Charger",
        name_hi="एमआई 33W सोनिकचार्ज चार्जर",
        category="chargers",
        unit="pc",
        cost_paise=76_900,
        sell_paise=109_900,
        popularity=1.60,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-SAM-25W",
        name="Samsung 25W Type-C Travel Adapter",
        name_hi="सैमसंग 25W टाइप-सी ट्रैवल अडैप्टर",
        category="chargers",
        unit="pc",
        cost_paise=90_900,
        sell_paise=129_900,
        popularity=1.20,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-AMB-20W",
        name="Ambrane 20W Type-C Charger",
        name_hi="एम्ब्रेन 20W टाइप-सी चार्जर",
        category="chargers",
        unit="pc",
        cost_paise=34_900,
        sell_paise=49_900,
        popularity=1.80,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-ERD-12W",
        name="ERD 12W Dual-USB Charger",
        name_hi="ईआरडी 12W डुअल-यूएसबी चार्जर",
        category="chargers",
        unit="pc",
        cost_paise=17_400,
        sell_paise=24_900,
        popularity=2.20,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-PORT-CAR24",
        name="Portronics Car Power 2.4A Car Charger",
        name_hi="पोर्ट्रोनिक्स कार पावर 2.4A कार चार्जर",
        category="chargers",
        unit="pc",
        cost_paise=24_400,
        sell_paise=34_900,
        popularity=0.80,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-BOAT-C-CBL",
        name="boAt Type-C A750 Cable 1.5m",
        name_hi="बोट टाइप-सी A750 केबल 1.5 मीटर",
        category="chargers",
        unit="pc",
        cost_paise=20_900,
        sell_paise=29_900,
        popularity=2.40,
        qty_choices=(1.0, 2.0),
    ),
    CatalogItem(
        sku="MB-MUSB-CBL",
        name="Micro-USB Cable 1m (local)",
        name_hi="माइक्रो-यूएसबी केबल 1 मीटर (लोकल)",
        category="chargers",
        unit="pc",
        cost_paise=6_900,
        sell_paise=9_900,
        popularity=1.80,
        qty_choices=(1.0, 2.0),
    ),
    CatalogItem(
        sku="MB-LTG-CBL",
        name="iPhone Lightning Cable (local)",
        name_hi="आईफ़ोन लाइटनिंग केबल (लोकल)",
        category="chargers",
        unit="pc",
        cost_paise=10_500,
        sell_paise=15_000,
        popularity=1.40,
        qty_choices=(1.0, 2.0),
    ),
    CatalogItem(
        sku="MB-AMB-C2C",
        name="Ambrane 60W C-to-C Cable 1m",
        name_hi="एम्ब्रेन 60W सी-टू-सी केबल 1 मीटर",
        category="chargers",
        unit="pc",
        cost_paise=20_900,
        sell_paise=29_900,
        popularity=1.00,
        qty_choices=(1.0, 2.0),
    ),
    CatalogItem(
        sku="MB-MI-PB10K",
        name="Mi Power Bank 3i 10000mAh",
        name_hi="एमआई पावर बैंक 3i 10000mAh",
        category="chargers",
        unit="pc",
        cost_paise=76_900,
        sell_paise=109_900,
        popularity=1.30,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-AMB-PB20K",
        name="Ambrane 20000mAh Power Bank",
        name_hi="एम्ब्रेन 20000mAh पावर बैंक",
        category="chargers",
        unit="pc",
        cost_paise=104_900,
        sell_paise=149_900,
        popularity=0.70,
        qty_choices=(1.0,),
    ),
    # ── audio ────────────────────────────────────────────────────────────────
    CatalogItem(
        sku="MB-BOAT-R255",
        name="boAt Rockerz 255 Pro+ Neckband",
        name_hi="बोट रॉकर्ज़ 255 प्रो+ नेकबैंड",
        category="audio",
        unit="pc",
        cost_paise=90_900,
        sell_paise=129_900,
        popularity=2.60,
        qty_choices=(1.0,),
        festival_affinity=1.30,
    ),
    CatalogItem(
        sku="MB-BOAT-AD141",
        name="boAt Airdopes 141 TWS Earbuds",
        name_hi="बोट एयरडोप्स 141 टीडब्ल्यूएस ईयरबड्स",
        category="audio",
        unit="pc",
        cost_paise=104_900,
        sell_paise=149_900,
        popularity=2.20,
        qty_choices=(1.0,),
        festival_affinity=1.40,
    ),
    CatalogItem(
        sku="MB-RLM-BUDS2",
        name="Realme Buds 2 Wired Earphones",
        name_hi="रियलमी बड्स 2 वायर्ड इयरफ़ोन",
        category="audio",
        unit="pc",
        cost_paise=41_900,
        sell_paise=59_900,
        popularity=1.60,
        qty_choices=(1.0,),
        festival_affinity=1.20,
    ),
    CatalogItem(
        sku="MB-JBL-C100SI",
        name="JBL C100SI Wired Earphones",
        name_hi="जेबीएल C100SI वायर्ड इयरफ़ोन",
        category="audio",
        unit="pc",
        cost_paise=55_900,
        sell_paise=79_900,
        popularity=1.10,
        qty_choices=(1.0,),
        festival_affinity=1.20,
    ),
    CatalogItem(
        sku="MB-BOAT-BH100",
        name="boAt Bassheads 100 Wired Earphones",
        name_hi="बोट बासहेड्स 100 वायर्ड इयरफ़ोन",
        category="audio",
        unit="pc",
        cost_paise=27_900,
        sell_paise=39_900,
        popularity=2.00,
        qty_choices=(1.0,),
        festival_affinity=1.20,
    ),
    CatalogItem(
        sku="MB-UBON-GP311",
        name="Ubon GP-311 Champ Wired Earphones",
        name_hi="यूबॉन GP-311 चैम्प वायर्ड इयरफ़ोन",
        category="audio",
        unit="pc",
        cost_paise=10_400,
        sell_paise=14_900,
        popularity=2.80,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-ZEB-COUNTY",
        name="Zebronics Zeb-County BT Speaker",
        name_hi="ज़ेब्रोनिक्स ज़ेब-काउंटी बीटी स्पीकर",
        category="audio",
        unit="pc",
        cost_paise=48_900,
        sell_paise=69_900,
        popularity=0.80,
        qty_choices=(1.0,),
        festival_affinity=1.30,
    ),
    CatalogItem(
        sku="MB-BOAT-ST350",
        name="boAt Stone 350 BT Speaker",
        name_hi="बोट स्टोन 350 बीटी स्पीकर",
        category="audio",
        unit="pc",
        cost_paise=125_900,
        sell_paise=179_900,
        popularity=0.60,
        qty_choices=(1.0,),
        festival_affinity=1.40,
    ),
    CatalogItem(
        sku="MB-BOULT-Z40",
        name="Boult Z40 TWS Earbuds",
        name_hi="बोल्ट Z40 टीडब्ल्यूएस ईयरबड्स",
        category="audio",
        unit="pc",
        cost_paise=76_900,
        sell_paise=109_900,
        popularity=0.90,
        qty_choices=(1.0,),
        festival_affinity=1.30,
    ),
    # ── covers ───────────────────────────────────────────────────────────────
    CatalogItem(
        sku="MB-CVR-NORD-SIL",
        name="OnePlus Nord CE4 Silicone Cover",
        name_hi="वनप्लस नॉर्ड CE4 सिलिकॉन कवर",
        category="covers",
        unit="pc",
        cost_paise=13_700,
        sell_paise=24_900,
        popularity=1.40,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-CVR-RN13-FLIP",
        name="Redmi Note 13 Flip Cover",
        name_hi="रेडमी नोट 13 फ्लिप कवर",
        category="covers",
        unit="pc",
        cost_paise=16_400,
        sell_paise=29_900,
        popularity=1.20,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-CVR-IP15-CLR",
        name="iPhone 15 Clear Case",
        name_hi="आईफ़ोन 15 क्लियर केस",
        category="covers",
        unit="pc",
        cost_paise=21_900,
        sell_paise=39_900,
        popularity=1.60,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-CVR-IP15-MAG",
        name="iPhone 15 Magsafe Case (local)",
        name_hi="आईफ़ोन 15 मैगसेफ़ केस (लोकल)",
        category="covers",
        unit="pc",
        cost_paise=27_400,
        sell_paise=49_900,
        popularity=0.80,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-CVR-M34-BACK",
        name="Samsung Galaxy M34 Back Cover",
        name_hi="सैमसंग गैलेक्सी M34 बैक कवर",
        category="covers",
        unit="pc",
        cost_paise=10_900,
        sell_paise=19_900,
        popularity=1.30,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-CVR-PRINTED",
        name="Printed Designer Cover (any model)",
        name_hi="प्रिंटेड डिज़ाइनर कवर (कोई भी मॉडल)",
        category="covers",
        unit="pc",
        cost_paise=8_200,
        sell_paise=14_900,
        popularity=3.00,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-CVR-VIVO-Y28",
        name="Vivo Y28 Candy Cover",
        name_hi="वीवो Y28 कैंडी कवर",
        category="covers",
        unit="pc",
        cost_paise=8_200,
        sell_paise=14_900,
        popularity=1.10,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-CVR-OPPO-A78",
        name="Oppo A78 Back Cover",
        name_hi="ओप्पो A78 बैक कवर",
        category="covers",
        unit="pc",
        cost_paise=10_900,
        sell_paise=19_900,
        popularity=0.90,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-CVR-POCO-X6",
        name="Poco X6 Carbon-Fibre Cover",
        name_hi="पोको X6 कार्बन-फ़ाइबर कवर",
        category="covers",
        unit="pc",
        cost_paise=10_900,
        sell_paise=19_900,
        popularity=0.90,
        qty_choices=(1.0,),
    ),
    # ── screen guards ────────────────────────────────────────────────────────
    CatalogItem(
        sku="MB-TG-11D",
        name="11D Tempered Glass (any Android)",
        name_hi="11D टेम्पर्ड ग्लास (कोई भी एंड्रॉइड)",
        category="screen_guards",
        unit="pc",
        cost_paise=5_000,
        sell_paise=9_900,
        popularity=3.00,
        qty_choices=(1.0, 2.0),
    ),
    CatalogItem(
        sku="MB-TG-OG-PRO",
        name="OG Pro Tempered Glass",
        name_hi="ओजी प्रो टेम्पर्ड ग्लास",
        category="screen_guards",
        unit="pc",
        cost_paise=9_900,
        sell_paise=19_900,
        popularity=1.60,
        qty_choices=(1.0, 2.0),
    ),
    CatalogItem(
        sku="MB-TG-IP15-PRIV",
        name="iPhone 15 Privacy Tempered Glass",
        name_hi="आईफ़ोन 15 प्राइवेसी टेम्पर्ड ग्लास",
        category="screen_guards",
        unit="pc",
        cost_paise=12_400,
        sell_paise=24_900,
        popularity=1.00,
        qty_choices=(1.0, 2.0),
    ),
    CatalogItem(
        sku="MB-TG-MATTE",
        name="Matte Gaming Tempered Glass",
        name_hi="मैट गेमिंग टेम्पर्ड ग्लास",
        category="screen_guards",
        unit="pc",
        cost_paise=7_400,
        sell_paise=14_900,
        popularity=0.90,
        qty_choices=(1.0, 2.0),
    ),
    CatalogItem(
        sku="MB-TG-UV-CURVED",
        name="UV Glue Glass (curved edge)",
        name_hi="यूवी ग्लू ग्लास (कर्व्ड एज)",
        category="screen_guards",
        unit="pc",
        cost_paise=17_400,
        sell_paise=34_900,
        popularity=0.50,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-LENS-GUARD",
        name="Camera Lens Guard",
        name_hi="कैमरा लेंस गार्ड",
        category="screen_guards",
        unit="pc",
        cost_paise=2_400,
        sell_paise=4_900,
        popularity=1.40,
        qty_choices=(1.0, 2.0),
    ),
    # ── storage ──────────────────────────────────────────────────────────────
    CatalogItem(
        sku="MB-SD-ULTRA64",
        name="SanDisk Ultra 64GB microSD",
        name_hi="सैनडिस्क अल्ट्रा 64GB माइक्रोएसडी",
        category="storage",
        unit="pc",
        cost_paise=46_600,
        sell_paise=54_900,
        popularity=1.80,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-SD-ULTRA128",
        name="SanDisk Ultra 128GB microSD",
        name_hi="सैनडिस्क अल्ट्रा 128GB माइक्रोएसडी",
        category="storage",
        unit="pc",
        cost_paise=76_400,
        sell_paise=89_900,
        popularity=1.20,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-HP-V236W32",
        name="HP v236w 32GB Pendrive",
        name_hi="एचपी v236w 32GB पेनड्राइव",
        category="storage",
        unit="pc",
        cost_paise=33_900,
        sell_paise=39_900,
        popularity=1.40,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-SD-CRUZER64",
        name="SanDisk Cruzer Blade 64GB Pendrive",
        name_hi="सैनडिस्क क्रूज़र ब्लेड 64GB पेनड्राइव",
        category="storage",
        unit="pc",
        cost_paise=50_900,
        sell_paise=59_900,
        popularity=0.90,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-SD-DUALGO64",
        name="SanDisk Dual Drive Go 64GB Type-C",
        name_hi="सैनडिस्क डुअल ड्राइव गो 64GB टाइप-सी",
        category="storage",
        unit="pc",
        cost_paise=63_600,
        sell_paise=74_900,
        popularity=0.60,
        qty_choices=(1.0,),
    ),
    # ── accessories ──────────────────────────────────────────────────────────
    CatalogItem(
        sku="MB-PHONE-STAND",
        name="Adjustable Phone Stand",
        name_hi="एडजस्टेबल फ़ोन स्टैंड",
        category="accessories",
        unit="pc",
        cost_paise=12_700,
        sell_paise=19_900,
        popularity=1.60,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-RING-LIGHT",
        name="10-inch Ring Light with Tripod",
        name_hi="10-इंच रिंग लाइट विद ट्राइपॉड",
        category="accessories",
        unit="pc",
        cost_paise=22_400,
        sell_paise=34_900,
        popularity=0.80,
        qty_choices=(1.0,),
        festival_affinity=1.20,
    ),
    CatalogItem(
        sku="MB-SELFIE-STICK",
        name="Selfie Stick with BT Remote",
        name_hi="सेल्फ़ी स्टिक विद बीटी रिमोट",
        category="accessories",
        unit="pc",
        cost_paise=19_100,
        sell_paise=29_900,
        popularity=0.90,
        qty_choices=(1.0,),
        festival_affinity=1.20,
    ),
    CatalogItem(
        sku="MB-WATCH-STRAP22",
        name="Smartwatch Strap 22mm Silicone",
        name_hi="स्मार्टवॉच स्ट्रैप 22mm सिलिकॉन",
        category="accessories",
        unit="pc",
        cost_paise=12_700,
        sell_paise=19_900,
        popularity=1.10,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-OTG-TYPEC",
        name="OTG Adapter Type-C",
        name_hi="ओटीजी अडैप्टर टाइप-सी",
        category="accessories",
        unit="pc",
        cost_paise=6_300,
        sell_paise=9_900,
        popularity=1.90,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-SIM-EJECT",
        name="SIM Ejector + Card Holder",
        name_hi="सिम इजेक्टर + कार्ड होल्डर",
        category="accessories",
        unit="pc",
        cost_paise=3_100,
        sell_paise=4_900,
        popularity=1.20,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-SKIN-WRAP",
        name="Mobile Skin Wrap (back)",
        name_hi="मोबाइल स्किन रैप (बैक)",
        category="accessories",
        unit="pc",
        cost_paise=12_700,
        sell_paise=19_900,
        popularity=0.70,
        qty_choices=(1.0,),
    ),
    CatalogItem(
        sku="MB-GAME-TRIGGER",
        name="Gaming Trigger L1R1 Pair",
        name_hi="गेमिंग ट्रिगर L1R1 जोड़ी",
        category="accessories",
        unit="pc",
        cost_paise=9_500,
        sell_paise=14_900,
        popularity=0.60,
        qty_choices=(1.0,),
    ),
)


MOBILE_CATALOG: Final[ShopCatalog] = ShopCatalog(
    key="mobile",
    categories=CATEGORIES,
    labels_hi=CATEGORY_LABELS_HI,
    shares=CATEGORY_SHARES,
    co_occurrence=CO_OCCURRENCE,
    margin_targets=CATEGORY_MARGIN_TARGET,
    items=at_trade_margin(_LISTED, CATEGORY_MARGIN_TARGET),
)
MOBILE_CATALOG.validate()
